### ISSUE TITLE
python3 is not supported?

### ISSUE THREAD

**Issue by mehdipourfar** [axiros/gevent_snmp#2]
I get the following error when I try to import async_session

> ImportError: /tmp/gevent_snmp/async_session.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyString_FromStringAndSize

**Comment by stephan-hof** [comment]
Now with
- https://github.com/axiros/gevent_snmp/commit/c47b79e03c2f76db4ff2966d93db9fdcfd42660f
- https://github.com/axiros/gevent_snmp/commit/449dfd7c9e01edde8176fb29e1b199976dba1447

python3 should be supported. Could you give it a try and report back how it is working ?

**Comment by stephan-hof** [comment]
>  One thing that i have observed was, it accepts python 2 str (bytes) for peername and community.

Yes and this is intended. The underlying library also requires just a plain `char*` so no unicode handling at all there. Also SNMP itself has no support for unicode as far as I know.

So image now somebody would do something like this as a community
```python
community = u"\u2603"
```

How should we convert it to plain bytes ? It is not `gevent_snmp` responsibilty to know this. It must be the user of the library knowing, how well my device does UTF-8 so I send the snowman as UTF8 encoded bytes.

> Are you planning to create a release with these changes?
Hmm currently not. However you can use master for now. We are not planning to make major changes there currently.
